#!/bin/bash
set -u  # undef is error
set -e  # stop at error

( echo -e "# FONT\tWEIGHT\tSLANT\tFILE" ;
    fc-list :outline -f '%{family}\t%{weight}\t%{slant}\t%{file}\n' |
    sort |
    uniq
) |
    column -t -s $'\t'
